@startuml


skinparam linetype ortho
skinparam shadowing false
skinparam backgroundColor White
skinparam defaultFontName Arial
skinparam defaultFontSize 16

skinparam state {
  BackgroundColor White
  BorderColor #333333
  
  FontColor #111111
  FontSize 10
  
  AttributeFontSize 14
  ArrowFontSize 10
  
  ArrowFontColor Red
  ArrowColor Black
  RoundCorner 90
}

Title Domain State Machine

state "Pending" as P {
P : CreatedAt
P : JobDefinition
P : JobId
}
state "Running" as R {
R : StartedAt
}

state "Terminal state " as T {
state "Succeeded" as S {
S : EndedAt
S : Result
S : ExitCode

}
state "Faulted" as F {
F : EndedAt
F : ErrorMessage
F : ExitCode
}
state "Cancelled" as C {
C : EndedAt
C : ErrorMessage
}
}   

[*] -down-> P : Create

P --down-> R : Start \n [G1]
P -down-> C : Cancel 

R --down--> S : Success\n [G2]
R -down-> F : Fault \n[G3]
R -down-> C : Cancel \n[G4]

S -down-> [*]
F -right-> [*]
C -right-> [*]

note right of T
  Terminal state.
  No outgoing domain transition.
end note

legend right
  |= Guard |= Meaning |
  | G1 | JobDefinition exists |
  | G2 | ExitCode == 0 |
  | G3 | ExitCode != 0 |
  | G4 | Run is not terminal |
endlegend
@enduml