@startuml

skinparam linetype ortho
skinparam shadowing false
skinparam backgroundColor White
skinparam defaultFontName Arial
skinparam defaultFontSize 16

skinparam state {
  BackgroundColor White
  BorderColor #333333
  FontColor #111111
  FontSize 10
  AttributeFontSize 14
  ArrowFontSize 10
  ArrowFontColor MediumVioletRed
  ArrowColor Black
  RoundCorner 18
}

state "Pending" as P {
P : CreatedAt
P : JobDefinition
P : JobId
}
state "Running" as R {
R : StartedAt
}

state "Terminal state " as T {
state "Succeeded" as S {
S : EndedAt
S : Result
S : ExitCode = 0

}
state "Faulted" as F {
F : EndedAt
F : ErrorMessage
F : ExitCode != 0
}
state "Cancelled" as C {
C : EndedAt
C : ErrorMessage
}
}   

[*] -down-> P

P -down-> R : Started
P -down-> C : Cancelled

R -down-> S : Succeeded
R -down-> F : Faulted
R -down-> C : Cancelled

S -right-> [*]
F -right-> [*]
C -right-> [*]

note right of S
  Terminal state.
  No outgoing domain transition.
end note
@enduml